services:
  streamlit:
    build: .
    working_dir: /opt/data-apps
    command: >
      bash -c "python3 -m streamlit run /opt/data-apps/streamlit/Data_Apps.py"
    ports:
      - "8501:8501"
    volumes:
      - ./:/opt/data-apps/
      - ./data-apps-logs:/var/log