services:
  streamlit:
    build: .
    working_dir: /opt/super-agent-tools
    command: >
      bash -c "python3 -m streamlit run /opt/super-agent-tools/streamlit/Super_Agent_Tools.py"
    ports:
      - "8501:8501"
    volumes:
      - ./:/opt/super-agent-tools/
      - ./super-agent-tools-logs:/var/log